### ISSUE TITLE
Error when rolling back transaction after performing only a SELECT query

### ISSUE THREAD

**Issue by sanmadjack** [jamesots/sqljocky#43]
When I run this code:

    Future _putMethod(RestRequest request) {
      return this._pool.startTransaction().then((mysql.Transaction tran) {
        return tran.prepare("SELECT * FROM files").then((mysql.Query query) {
          return query.execute().then((result) {
            // Do something?
          }).then((_) {
            this._log.info("Closing");
            query.close();
          });
        }).then((_) {
          this._log.info("Rolling");
          return tran.rollback().then((_) {
            this._log.info("Rolled");
          });
        });
      });
    }

I get this output:

2014-07-04 14:35:46.528: INFO: (ConnectionPool) Starting transaction
2014-07-04 14:35:46.572: INFO: (FilesResource) Closing
2014-07-04 14:35:46.573: INFO: (FilesResource) Rolling
2014-07-04 14:35:46.574: SEVERE: (RestServer) MySQL Client Error: Connection #0 cannot process a request for Instance of '_QueryStreamHandler' while a request is already in progress for Instance of '_ExecuteQueryHandler'
Uncaught Error: Bad state: Future already completed
Stack Trace: 
#0      _AsyncCompleter.completeError (dart:async/future_impl.dart:35)
#1      _handleData (package:sqljocky/src/connection.dart:211:31)
#2      _rootRunUnary (dart:async/zone.dart:730)
#3      _RootZone.runUnary (dart:async/zone.dart:864)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:571)
#6      _Future._completeWithValue (dart:async/future_impl.dart:331)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:393)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:128)

Am I doing something wrong?

**Comment by jamesots** [comment]
Not fixed properly - need to do more work on this.
